---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: instana-qm-config-updater
  namespace: instana-agent

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: instana-qm-config-updater-role
rules:
- apiGroups: ["mq.ibm.com"]
  resources: ["queuemanagers"]
  verbs: ["get", "list"]
- apiGroups: ["instana.io"]
  resources: ["agents"]
  verbs: ["get", "list", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rolebinding-instana-qm-config-updater
subjects:
- kind: ServiceAccount
  name: instana-qm-config-updater
  namespace: instana-agent
roleRef:
  kind: ClusterRole
  name: instana-qm-config-updater-role
  apiGroup: rbac.authorization.k8s.io